### ISSUE TITLE
AArch64 Continuous Integration Pipeline

### ISSUE THREAD

**Issue by almann** [amazon-ion/ion-rust#104]
#102 illustrates that we should have some kind of CI for AArch64 if we want to ensure that things build/run on this platform.  A quick survey on Github Actions doesn't make it clear that it is an option here, but regardless, we should do something for ARM.

**Comment by therapon** [comment]
Github Actions seem to support it at the moment only with hosting your own runner (bring your own) https://docs.github.com/en/actions/hosting-your-own-runners
