### ISSUE TITLE
Ion Element/Value API

### ISSUE THREAD

**Issue by rhinomode** [amazon-ion/ion-rust#114]
Hello, this is a request for enhancing/extending the functionality provided to Rust Ion users.

The [IonJava ](https://github.com/amzn/ion-java) and [IonElement](https://github.com/amzn/ion-element-kotlin) libraries provide useful abstractions over Ion readers and writers (which themselves are very useful).

As a user of the `ion-rs` crates, I find myself wanting a API similar to those found in the Java libraries (above) or the [`serde-rs/json`](https://github.com/serde-rs/json) crate. 

The reason is simple: to make sensible code, I must build structures (`enum` even) around the `ion-rs/*` functions and constants. Then I must also consider all of the other low-level concerns of (lazily) materializing, (avoiding) clones of effectively immutable data to satisfy the borrow checker, etc. etc.

I suspect can and should be "solved once" as in the Java prior art.

Thanks,
Chuck

**Comment by rhinomode** [comment]
There's some[ interesting test code](https://github.com/amzn/ion-rust/blob/master/ion-c-sys/tests/value.rs) from Almann along these lines in the `ion-c-sys` crate - obviously not meant for consumption outside the test harness.

**Comment by almann** [comment]
#132 also makes further progress on this.

**Comment by zslayton** [comment]
The `Element` API has been heavily revised (see: #479, #485, #486, #487); these changes will be included in the next release.
