### ISSUE TITLE
Loader can only be built from bytes

### ISSUE THREAD

**Issue by marcbowes** [amazon-ion/ion-rust#201]
```
    fn iterate_over<'a>(
        &'a self,
        data: &'a [u8],
    ) -> IonResult<Box<dyn Iterator<Item = IonResult<OwnedElement>> + 'a>>;
```

This signature is a little restrictive because you need the data slice. If you have a reader already (but not the bytes) you can't use this API. Maybe it should accept something like `TryInto<IonCReaderHandle<'a>, Error = IonError>` or similar.

**Comment by zslayton** [comment]
`Element::iter()` accepts anything that implements `io::Read`.
