### ISSUE TITLE
Improve Timestamp value

### ISSUE THREAD

**Issue by marcbowes** [amazon-ion/ion-rust#209]
Currently you can make one but beyond that it's not very useful, this comment is right on:

```
// TODO: Timestamp does not yet provide useful accessors for its individual fields. It can be
//       instantiated and tested for equality, but will not very useful as a general purpose
//       datetime until these methods are added.
```

It'd be nice to have something like what Decimal provides - a try from implementation into a Chrono type.

**Comment by almann** [comment]
I think `TryFrom<DateTime<FixedOffset>>` makes a lot of sense, but it sounds like you might want something to extract back to a `DateTime<FixedOffset>` or the like, yes?

**Comment by marcbowes** [comment]
Yeah. I really just want to print the timestamp in ISO8601, and `DateTime<FixedOffset>` seems like a good stepping stone.

**Comment by almann** [comment]
I have a strong preference for leaving the `Timestamp` wrapper we have as a type that holds the precision and offset and allowing `into` type methods to get the `chrono` types out that have all the operators, this way we don't chase the `chrono` APIs but keep things ergonomic and cheap to convert into and out of the wrapper.

**Comment by almann** [comment]
My thoughts are a minimal surface for this would be to implement `Display` for the RFC string and a method like:

```rust
fn to_date_time(&self) -> DateTime<FixedOffset>
```

To provide the conversion (we should also have `Into<DateTime<FixedOffset>>`, but that requires a value).  My read of `chrono` is that this conversion is pretty cheap.

**Comment by popematt** [comment]
There are now field accessors for all fields, except for fractional seconds (sort of). You can read fractional seconds as nanoseconds or milliseconds, but fractional seconds will be truncated for any precision higher than nanoseconds. (See https://docs.rs/ion-rs/0.18.1/ion_rs/types/struct.Timestamp.html)

**Comment by zslayton** [comment]
I've opened #611 to track accessing higher precisions than nanoseconds. I'm going to close this issue out now that we have accessors for everything else.
