### ISSUE TITLE
[ion-c-sys] `ionc!` macro should have more Information in Error

### ISSUE THREAD

**Issue by almann** [amazon-ion/ion-rust#242]
We should expand `IonCError` to store some expression/file/line information to make the errors more useful:

> Yes, and we probably want a field that helps capture other context too.  E.g. `ionc!` should be able to `stringify!` the expression itself plus `file!` and `line!` to make it a bit clearer where the error originated--this should actually be the easiest thing to add.

_Originally posted by @almann in https://github.com/amzn/ion-rust/issues/234#issuecomment-831006377_

**Comment by almann** [comment]
Fixed in #234

**Comment by marcbowes** [comment]
Reopening. I don't think we did the stringify work.
