### ISSUE TITLE
Chrono timestamps always have precision

### ISSUE THREAD

**Issue by marcbowes** [amazon-ion/ion-rust#293]
```
2000-01-01T00:00:00+00:00 -> [69, 80, 0f, d0, 81, 81, 80, 80, 80, c9]
```

So the first type is 68 not 69 (because my output has +1 byte) and the last (extra) byte is c9. I think that's because the above example shows up with 0d-9 nanoseconds. So... looks like 2 bugs! If you don't mind, I'll open (and own) and issue for the second one (treat is as orthogonal to this PR).

_Originally posted by @marcbowes in https://github.com/amzn/ion-rust/pull/289#discussion_r653173492_

**Comment by zslayton** [comment]
Support for `chrono` timestamps has been removed.
