### ISSUE TITLE
Roadmap or Todo list towards production release

### ISSUE THREAD

**Issue by heri16** [amazon-ion/ion-rust#297]
Is there a roadmap before this library can be considered ready for production/beta?

**Comment by zslayton** [comment]
Please see [milestone 1](https://github.com/amazon-ion/ion-rust/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22v1.0+Release%22) for this. We're stabilizing the `Element` API for reading and writing values for v1.0; stable support for `serde` and the streaming readers/writers will follow.
