### ISSUE TITLE
Address clippy complaints about ion-c bridge code 

### ISSUE THREAD

**Issue by zslayton** [amazon-ion/ion-rust#361]
A recent build of clippy [started rejecting calls to some `ion-c` functions that take `ION_TYPE` as a parameter](https://github.com/amzn/ion-rust/pull/360/commits/320aca465516a997128c30e503a65493f4713ff1#diff-dcf9e09c7c7ed25f36d99db555c71c31d59a380a4a2e4d6529ce1411de9490e4), claiming that they risk dereferencing a raw pointer and so should be marked unsafe. Strangely, it doesn't seem to apply to all such functions.

I've added [`#[allow(clippy::not_unsafe_ptr_arg_deref)]` to those methods](https://github.com/amzn/ion-rust/pull/360/files#diff-dcf9e09c7c7ed25f36d99db555c71c31d59a380a4a2e4d6529ce1411de9490e4) as part of #360, but we should follow up.

cc @almann

**Comment by popematt** [comment]
`ion-c` bridge code has been removed.
