### ISSUE TITLE
Cannot read value of a Decimal

### ISSUE THREAD

**Issue by trashbyte** [amazon-ion/ion-rust#405]
I cannot find any way to get the actual underlying value of a `Decimal` object. The `Decimal` type is opaque and the `coefficient` field is not publicly exposed in any way I can find, aside from being printed by the `Display` implementation, which is hardly an efficient way to access the value. Am I missing something? Is this an intentional design choice?

**Comment by zslayton** [comment]
>  Is this an intentional design choice?

No, the library is simply incomplete. 

At present, both `Decimal` and `Timestamp` are difficult to use as standalone types. They have enough functionality to guarantee fidelity during roundtripping, but not to use them on their own.

See #286 and #273.

**Comment by rmarrowstone** [comment]
Another relevant issue is the discussion around using BigDecimal: https://github.com/amzn/ion-rust/issues/302

**Comment by rmarrowstone** [comment]
I've been looking at this today and my current thinking is that we should _not_ export and in fact remove all dependencies on `BigDecimal`. We should prefer to keep our dependencies lean and it is not clear that `bigdecimal` is the obvious choice, so I don't think we want to be opinionated about this. I realize that we are also using the `num` crates, but they are much more commonly used: they have more forks and stars and are used in the aws-sdk-rust, for example.

As of https://github.com/amzn/ion-rust/pull/365 our `Decimal` exposes `scale` and `precision`. I propose that we expose the bare minimum to be usable: the magnitude of the decimal and the sign.

Users will need to write their own arithmetic or convert our `Decimal` to their chosen representation, but they will have one less dependency forced on them. We can also later enrich our `Decimal` model further if needed. Additionally, If there is a clear de facto standard crate in time we can provide transforms to/from that.
