### ISSUE TITLE
Should the text format outputs end with a newline?

### ISSUE THREAD

**Issue by jobarr-amzn** [amazon-ion/ion-rust#437]
I'd argue that at least the `pretty` and `lines` formats (which have newlines at least between top level values) should be newline-terminated.

https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file

**Comment by zslayton** [comment]
The new `Writer` that replaced `IonWriter`+impls (in `v1.0.0-rc.4`) does not have this issue.
