### ISSUE TITLE
Implement `Display` for `value::owned::Struct`, `value::owned::Sequence`, etc.

### ISSUE THREAD

**Issue by jpschorr** [amazon-ion/ion-rust#447]
`value::owned::Element` implements `Display`: https://github.com/amzn/ion-rust/blob/main/src/value/owned.rs#L456-L483

But e.g., `Struct`, `Sequence` to not implement `Display`

So if I have a `Struct` (perhaps I've checked type and called `as_struct` on the `Element` and passed to another function), I can't easily display without something like `Element::from(struct_.clone()).to_string()`

**Comment by zslayton** [comment]
Fixed in #486, this will be included in the next release.
