### ISSUE TITLE
Mitigation of 3P BigInt in Public API

### ISSUE THREAD

**Issue by almann** [amazon-ion/ion-rust#507]
Currently, we expose a 3P `num_bigint::BigInt` (and friends) in our public API.  This is a problem as our stability is a moving target and `num_bigint` is also pre-1.0.  We have a few options here:

1. Wrap `BigInt` in our APIs (similar to what we do in `Decimal` and `Timestamp`), let's call this `LargeInt` for the purposes of discussion.
1. Eliminate `BigInt` entirely and replace with `i128` as a _good enough_:tm: solution.  @zslayton suggested this and may prefer it.
1. Re-export `num_bigint` into `ion_rs::external::num_bigint` and make all of our type references line up to this.  This is effectively aliasing the type in our crate.

I am of the opinion that we should do (3) and provide a `TryInto<i128>` for the `Int` enum and `TryInto<u128>` for the `UInt` enum.  If, and only if, we have a compelling reason to create `LargeInt` should we do so.

(1) and (3) have the problem that a user consuming our wrapper with a local dependency of `BigInt` still requires conversion code (even for `LargeInt`), but is tractable (we cannot auto generate this code, but we could maybe provide a macro to generate the conversion assuming structure of the API--TBH, I don't love this).

(2) has the problem that integers over 16-bytes cannot be represented.  In practice this is probably okay as we're talking integers in the range`-170,141,183,000,000,002,920,328,542,032,742,055,937` to `170,141,183,000,000,002,920,328,542,032,742,055,936`.  I find this disappointing because it would be a regression of functionality only because of the 3P dependency (we wouldn't naturally do this if `BigInt` was in `std`).

**Comment by popematt** [comment]
**Option 4**
Fundamentally, the problem is that we have a transparent `Int` (and `UInt`) enum.

If we make `Int` opaque to hide the underlying implementation, then we can do whatever we want behind the scenes.
We can provide:
* `impl TryFrom<Int> for i128` -- *good enough*™️ for most cases
* `impl From<Int> for Vec<u8>` -- where Vec<u8> is the 2's complement representation of the integer value; this is a lowest-common-denominator format that consumers of the library can use to convert from our opaque int to their own biggish-int type.

In the future, if we deem this soution insufficient, it would be backwards compatible to introduce a `LargeInt` and add `From<Int> for LargeInt` or to re-export `BigInt` and add `impl From<Int> for BigInt`.

**Comment by almann** [comment]
I would be fine making `Int` an opaque wrapper over the underlying `enum` and providing conversions into/out of the various built-in integer types and accessor APIs around them.

I am less inclined to expose `From<Int> for Vec<u8>` because that is a _parsing_ concern and in general these _big integer_ types are generally arrays/vectors of words not octets.  So in practice we'll make things worse for that case.

If we go this route, I still believe we make `ion_rs::external::num_bigint` and provide conversion/access for `BigInt` against the re-exported type (this type has methods to de-structure its contents, IIRC).

A real use case is dealing with the primitive versus large case which is why the `enum` is public today.  Making client code not be able to `match` against small vs. big when parsing seems like a usage regression to me--I would be interested in how we envision the code working for that.  Maybe we introduce a data-less enum for this to maintain the opaqueness of the contents.

```rs
/// Smallest integer that an [`Int`] can fit in without failing conversion.
enum IntSize {
  I64, I128, Large
}

struct Int { ... }

impl Int {
  fn size() -> IntSize { ... }
  ...
}
```

**Comment by popematt** [comment]
> Maybe we introduce a data-less enum for this to maintain the opaqueness of the contents.

Yes. I think this is a good idea.

> I am less inclined to expose From<Int> for Vec<u8> because that is a parsing concern and in general these big integer types are generally arrays/vectors of words not octets. So in practice we'll make things worse for that case.

I went and looked at the docs for a few big integer types, and I have changed my mind on this. It's possible to add a `to_u64_digits()` function, which would make it really straightforward for a consumer to convert to their own `BigInt` dependency, but there doesn't seem to be a common way to make it easy to convert to some of the other biggish-int crates like `ramp` or `apint`.

If we do re-export `BigInt`, will it be a potentially breaking change for consumers if we upgrade the exported version of the `num_bigint` crate? If so, I could see that being a reason to create a `LargeInt` wrapper.

**Comment by almann** [comment]
> If we do re-export `BigInt`, will it be a potentially breaking change for consumers if we upgrade the exported version of the `num_bigint` crate? If so, I could see that being a reason to create a `LargeInt` wrapper.

It _could_ be a breaking change.  But to be honest, our API stability is considerably worse than `num_bigint`, so I think deferring on this decision is a good idea especially if we add `i128`/`u128` APIs.  `num_bigint` hasn't changed since November 2021, so I think it is pretty stable.

**Comment by popematt** [comment]
There's some interesting discussion in https://github.com/rust-lang/api-guidelines/discussions/176 around whether to re-export that might be helpful to consider. (Though I suspect that you are already aware of all the points that they raise, Almann.)

**Comment by zslayton** [comment]
`UInt` and `Int` are now opaque structs rather than enums, so `BigInt` and `BigUint` are no longer part of the public API. `Into` and `TryInto` implementations for the various native Rust integer types are provided for `UInt`/`Int`.

There's still room for adding something like `to_u64_digits()`, but I'd like to punt on that until we have a request for it. I've opened #603 to track it.
