### ISSUE TITLE
Consider changing the return type of `Decimal::precision()` to `NonZeroU64`

### ISSUE THREAD

**Issue by popematt** [amazon-ion/ion-rust#581]
The `precision()` function of `Decimal` cannot return `0`. We can signal and enforce that invariant using the type system if we change the return type from `u64` to `NonZeroU64`.

**Comment by zslayton** [comment]
In this particular case, I think the loss of ergonomics is likely not worth the optimized memory layout for types like `Option<NonZeroU64>`. I think it will be relatively rare for folks to calculate the precision and then store it in an `Option<_>`.

I think we could very easily switch the return type to `usize`, though.

**Comment by popematt** [comment]
Is the precision actually limited to `usize`? I.e. is it impossible to create a `Decimal` with a precision that is greater than `usize::MAX`?

**Comment by zslayton** [comment]
Per offline discussion, we're going to stick with `u64` for decimal precision as it aligns well with the `i64` used for exponent and scale. It is technically possible (with enough hardware!) for a `UInt` to have more digits than a `u64` can represent, but 18 quintillion digits is probably sufficient.
