### ISSUE TITLE
Add an `IonError::Application` variant

### ISSUE THREAD

**Issue by zslayton** [amazon-ion/ion-rust#583]
`IonError`'s variants are not intended to be constructed by end users. However, if a user is writing code to work with Ion, they may wish to bubble up an error of their own without refactoring all of their method signatures to use a custom error type. We should consider adding an `Application` error type that takes (initially, at minimum) a `String` description of the problem.

**Comment by popematt** [comment]
I don't know of a compelling use case for an `Application` error type _unless_ part of our API accepts a closure/function that returns a Result. In that case, it _may_ be convenient for a user to be able to create an `Application` error.

**Comment by zslayton** [comment]
This issue was originally motivated by the observation that our test suites were constructing their own `IonResult`s to bubble up errors instead of the more correct (but tedious) approach of using their own error types. I agree that the use case is pretty weak. The closure observation is a good one! I don't think we have something like that for now.

In any case, PR #584 marked `IonError` as `non_exhaustive`, so we can add other variants down the line without a breaking change.

**Comment by zslayton** [comment]
Closing this until we have a more compelling concrete use case.
