### ISSUE TITLE
`Symbol` implements `PartialEq<Symbol>` for `&str` instead of `str`

### ISSUE THREAD

**Issue by sadderchris** [amazon-ion/ion-rust#610]
There's a `PartialEq` impl for `&str` [here](https://github.com/amazon-ion/ion-rust/tree/main/src/types#L196).  This isn't quite right though, since it means that if you want to compare a symbol against a string literal, you need to put the string literal behind a reference, like so:

```rust
if symbol == &"text" {
    // do something
}

// rather than

if symbol == "text" {
    // do something
}
```

The impl should probably be

```rust
impl PartialEq<Symbol> for str {
    fn partiql_eq(&self, other: &Symbol) -> bool {
        // existing impl
    }
}
```

**Comment by zslayton** [comment]
Good catch! Thanks for reporting this.
