### ISSUE TITLE
Can Element be made to implement Send and Sync?

### ISSUE THREAD

**Issue by dlurton** [amazon-ion/ion-rust#615]
Can `Element` be made to implement `Send` and `Sync`?

[Note: This issue originally was longer and titled differently--I have since found a simple solution so the original text was moot.  However, the question posed above still is a valid one, I think.]

**Comment by dlurton** [comment]
I did also find a [solution that was easier than I initially suggested]((https://github.com/dtolnay/async-trait#non-threadsafe-futures).  , which does work without introducing new scopes.

**Comment by zslayton** [comment]
`Element` does implement `Send`, as demonstrated by this unit test:
https://github.com/amazon-ion/ion-rust/blob/d35d6aea95089f40c1855cc2fe5c2c79675a99a8/src/element/mod.rs#L1499-L1513

This change was made in PR #497. 

`Element` is immutable (with cloning builders to make modified copies); does it also need to implement `Sync`?

**Comment by dlurton** [comment]
Ah, looks like my team was using `0.16` and the `Send` impl was released in `0.17`.  Thanks.

My specific use case was around `Send`, I don't think I have a specific use for `Sync` at this time--I was just adding that out of curiosity.
