### ISSUE TITLE
`element_stream_*` items not available in `v1.0.0-rc.1`

### ISSUE THREAD

**Issue by jpschorr** [amazon-ion/ion-rust#624]
`element_stream_reader` and `element_stream_writer` are imported into `element` via experimental feature flags here:
https://github.com/amazon-ion/ion-rust/blob/31ec96137a585d8399b4bfd87a3685c78de5909d/src/element/mod.rs#L36-L39

But `mod element` is brought in privately, and `element_stream_*` items are never `pub use`d. See here: https://github.com/amazon-ion/ion-rust/blob/31ec96137a585d8399b4bfd87a3685c78de5909d/src/lib.rs#L184

Are they intended to be public? If so, I would presume the would be `use`d 
- https://github.com/amazon-ion/ion-rust/blob/31ec96137a585d8399b4bfd87a3685c78de5909d/src/lib.rs#L217-L218
- https://github.com/amazon-ion/ion-rust/blob/31ec96137a585d8399b4bfd87a3685c78de5909d/src/lib.rs#L235-L236

**Comment by desaikd** [comment]
Currently element reader APIs are available through: https://github.com/amazon-ion/ion-rust/blob/main/src/element/reader.rs#L16. `element_stream_*` APIs are intended to be private for 1.0.0 release in favor of the above mentioned APIs.
