### ISSUE TITLE
Convert serde_json::Value to Ion

### ISSUE THREAD

**Issue by jplock** [amazon-ion/ion-rust#803]
My API allows people to pass arbitrary JSON payloads in a request body. Through Axum I’m converting the payload into a serde_json::Value. I’d like to convert this into an Ion binary value and store it (in DynamoDB). 

What’s the best way to do the conversion if I don’t care about the schema?

**Comment by popematt** [comment]
>  if I don’t care about the schema?

I'm assuming you mean "without serde-annotated structs".

You would need to define a mapping from `serde_json::Value` to `ion_rs::Element`, such as this:

```rust
use ion_rs::{Element, IonType, List, Sequence, Struct};
use serde_json::{Value};

fn json_to_ion(value: Value) -> Element {
    match value {
        Value::Null => Element::null(IonType::Null),
        Value::Bool(b) => Element::boolean(b),
        Value::Number(n) => {
            todo!("Choose a number conversion strategy")

            // == Convert Number to Ion float and Ion int ==
            // if let Some(i) = n.as_i64() {
            //     Element::int(i)
            // } else if let Some(i) = n.as_u64() {
            //     Element::int(i)
            // } else if let Some(f) = n.as_f64() {
            //     Element::float(f)
            // } else {
            //     unreachable!()
            // }

            // == Convert all Number to Ion decimal ==
            // if let Some(i) = n.as_i64() {
            //     Element::decimal(i.into())
            // } else if let Some(i) = n.as_u64() {
            //     Element::decimal(i.into())
            // } else if let Some(f) = n.as_f64() {
            //     Element::decimal(f.try_into().expect("Infinite or NaN values are not JSON numbers."))
            // } else {
            //     unreachable!()
            // }

            // One could also convert float Numbers to Ion decimal and integer Numbers to Ion int
        }
        Value::String(s) => Element::string(s),
        Value::Array(values) => List(
            values
                .into_iter()
                .map(|v| json_to_ion(v))
                .collect::<Sequence>(),
        )
        .into(),
        Value::Object(values) => values
            .into_iter()
            .map(|(k, v)| (k, json_to_ion(v)))
            .collect::<Struct>()
            .into(),
    }
}
```
(Constructing the List is more awkward than it needs to be; I've created #811 to address that.)

Then, assuming you are using `ion-rs v1.0.0-rc.6`, to write the data to binary Ion, you can use [`encode_as(Binary)`](https://docs.rs/ion-rs/1.0.0-rc.6/ion_rs/struct.Element.html#method.encode_as)

Does this help? (Have I understood your question correctly?)

**Comment by jplock** [comment]
Yes, correct. No serde annotated structs. This gives me a good starting point. Thanks!

**Comment by jplock** [comment]
Follow up question, is there anyway to go from a Vec<u8> representing a JSON byte string directly into Ion or do I need to convert to a serde_json::Value first?

**Comment by jplock** [comment]
Yes serialized JSON. The read_one method sounds like it will work for my use case. I’ll try it out. Thanks again!
