### ISSUE TITLE
[ion-c-sys] Support for Decimal Signed Zero in High-Level APIs

### ISSUE THREAD

**Issue by almann** [amazon-ion/ion-rust#83]
`bigdecimal::BigDecimal` relies on `num_bigint::BigInt` to provide the signed coefficient.  `BigInt` does not support maintaining sign when constructing it ([`bigint.rs` L2774-2786][1]).  This information is lost when converting from `ION_DECIMAL` to `BigDecimal`, so we should have some kind of API to preserve this if so desired.

One can always use `ION_DECIMAL` and `IonDecimalPtr` to get at the low-level Ion C APIs, but they shouldn't have to.

[1]: https://github.com/rust-num/num-bigint/blob/7562ab24330792817e42b808f60b0cac51ca261a/src/bigint.rs#L2774-L2786

**Comment by marcbowes** [comment]
I think the issue might be deeper than that. Loading `-0d0` and stepping through the code in `try_to_bigdecimal`, I see that the sign is lost.. `signum` is set to 0 and calling `ion_decimal_is_negative` returns false.

**Comment by zslayton** [comment]
I believe we opened this issue before [the `Decimal` type](https://github.com/amzn/ion-rust/blob/a23433aa270122171b429d123e0c66ddfa2e00e4/src/types/decimal.rs#L13-L17) existed. `Decimal` maintains the sign information and [provides conversions to/from `BigDecimal`](https://github.com/amzn/ion-rust/blob/a23433aa270122171b429d123e0c66ddfa2e00e4/src/types/decimal.rs#L153-L181). (Like `Timestamp`, it currently serves to preserve fidelity and not very useful on its own.) `ion-c-sys` could provide a `try_to_decimal` alongside `try_to_bigdecimal`.

**Comment by zslayton** [comment]
In retrospect, this would create a circular dependency between `ion-rust` and `ion-c-sys`. We'd need to do some refactoring. (A new `ion-rust-types` crate? Bleh.)

**Comment by almann** [comment]
@zslayton is correct, this all predates the higher-level APIs in `ion-rs`.  I don't think we need to refactor the types here, what we can do is preserve the sign information by returning it in an API like `try_to_bigdecimal() -> Result<IonCDecimal>` or some such.

Just to spit-ball, something that looks like this might be sufficient:

```rust
/// Wrapper over [`BigDecimal`] to preserve signed zero cases
pub enum IonCDecimal {
    Normal(BigDecimal),
    /// Negative zero with an exponent
    NegativeZero(i64)
}

// implement `Into<BigDecimal>` and/or provide an `into_decimal` type API to unwrap. 
```

**Comment by marcbowes** [comment]
Even if we do the enum thing, how do we know to make a `IonCDecimal::NegativeZero(..)`? I played around with the ion-c APIs last night and I just couldn't figure it out! Of all the APIs, only the to_string one included the negative sign.

**Comment by marcbowes** [comment]
I think the issue is https://github.com/amzn/ion-c/blob/2671a0835ea8b60d7bf8df17ce9eb61f75458d9d/ionc/ion_int.c#L731 where we return before setting signum to either 1 or -1.

**Comment by almann** [comment]
This looks right--I hadn't actually looked at if upstream supported negative zero correctly, but it looks like we're going to have to fill that in as a prerequisite for this issue.
