### ISSUE TITLE
How to stream binary and `Serialize`-ed data?

### ISSUE THREAD

**Issue by barries** [amazon-ion/ion-rust#856]
We've prototyped a mixed-mode streaming + Serde `Serialize` logger for our applications using CBOR and would like to switch to Ion, but I'm struggling to find examples or docs that show how to do this.

From reading the source code, it seems like what I need to do is:

1. Instantiate a `BinaryWriter<>` and use it for the lifetime of the log
2. `step_in()`,
3. encode a timestamp and a metadata field or two,
4. Serde-`serialize()` one or more data structures using the experimental-unstable-but-complete-and-highly-tested Serde serializer, then
    * _in some cases we would instead encode some things using the streaming interface, like images or `Debug` formatted strings_ 
5. `step_out()`
6. Repeat 1...5 for each additional log entry

Below is my non-working draft to show what I mean. The first error after my broken import attempt is that `step_in()` isn't defined for `Writer<...>` (error text below).

Is there some documentation or example for how to use these APIs effectively in `ion-rs`? If not, is there any advice or example snippets the experts here can share?

```rust
pub struct Log {
    writer: ion_rs::v1_0::BinaryWriter<BufWriter>,
    ...
}

pub fn init(path: Option<String>) -> io::Result<()> {
    use ion_rs::v1_0;
    ...

    let writer = ion_rs::v1_0::BinaryWriter::<BufWriter>::new(
        v1_0::Binary,
        BufWriter(Vec::with_capacity(INITIAL_BUFFER_CAPACITY))
    ).expect("BinaryWriter::new() failed");

    let m = Mutex::new(
        Log {
            writer:     writer,
            ...

        }
    );
    ... store m in a global ...
    Ok(())
}

unsafe impl Send for Log {} // Allow BinaryWriter to be Send; it has a pointer in it that's ok to share (pointers are !Send as a lint to the author, not due to inherent unsafety)

impl Log {
    pub fn write_entry_start(&mut self, module_path: &str, event_kind: EventKind) {
        use ion_rs::Writer::*;
        use chrono::Utc;

        self.writer.step_in(ion_rs::IonType::List);
        let now: crono::DateTime = Utc::now();
        let event_timestamp = ion_rs::Timestamp::from_datetime(now, ion_rs::TimestampPrecision::Second);
        self.writer.write(event_timestamp);
        let event_source = format!("{:?}::{module_path}", EventSource::iotaSOFT_UI);
        self.writer.write(event_source);
        self.writer.write(format!("{:?}", event_kind));
    }

    pub fn write_entry_end(&mut self) {
        self.writer.step_out();
    }

    pub fn flush(&mut self) {
        self.writer.flush();
    }

    pub fn write_named_value(&mut self, name: &str, value: &impl serde::Serialize) {
        self.writer.write_symbol(name);

        let mut s = // TODO: Instantiate Ion Serde Serializer;
        let _ = value.serialize(&mut s);
    }
```

```
error[E0432]: unresolved import `ion_rs::Writer`
   --> src\uilog.rs:250:21
    |
250 |         use ion_rs::Writer::*;
    |                     ^^^^^^ `Writer` is a struct, not a module

error[E0599]: no method named `step_in` found for struct `Writer` in the current scope
   --> src\uilog.rs:253:21
    |
253 |         self.writer.step_in(ion_rs::IonType::List);
    |                     ^^^^^^^ method not found in `Writer<Binary, BufWriter>`
...
```

**Comment by barries** [comment]
Well, TBH, the rc9 docs don't show `Writer`, `ListWriter`, etc. (I may be missing something else about how the docs server works, feel free to cluebat me), so I can't figure out the details. Based on your example (thanks!!!), I'm guessing I want to use `value_writer().list_writer()` to write each log entry as a list--and that seems to work, yay!.

However, I need to either (a) return or (b) pass the value returned by `list_writer()` so that either (a) calling code use it, or (b) it can be passed to a closure that uses it. 

The following code, based on your example, works the `write_content` parameter and call commented out. How can I specify a type _like_ `LogWriter::ValueWriter::ListWriter` as the closure parameter for `write_entry()`'s `write_content: impl FnOnce(...)`?

```rust
pub struct Log {
    writer: LogWriter,
    file:   File,
}
...
    let m = Mutex::new(
        Log {
            writer: writer,
            file:   File::create(log_file_path.clone())?,
        }
    );
    ... use m to call write_entry(...) ...
...
    pub fn write_entry(&mut self, module_path: &str, event_kind: EventKind, write_content: impl FnOnce(SequenceWriter)) {
        use chrono::Utc;

        let mut list_writer = self.writer.value_writer().list_writer().expect("logger ListWriter creation failed");

        let now = Utc::now().naive_utc();
        let event_timestamp = ion_rs::Timestamp::from_datetime(now, ion_rs::TimestampPrecision::Second);
        let _ = list_writer.write(event_timestamp);
        let event_source = format!("{:?}::{module_path}", EventSource::iotaSOFT_UI);
        let _ = list_writer.write(event_source);
        let _ = list_writer.write(format!("{:?}", event_kind));

        write_content(list_writer);

        let _ = list_writer.close();
    }
```

Thanks for the help!!!

**Comment by barries** [comment]
No need for the example--let me play with your guidance. I don't want to burden you with trivialities, and you've been immensely helpful.

I was going to ask how to learn about Ion v1.1 support--like, where to find what's even in the 1.1 spec--my Google Fu has so far not turned up a draft 1.1 spec or a delta....

**Comment by barries** [comment]
Thanks! Those docs are indeed much better, though I can't find an answer to "How can I specify a type like LogWriter::ValueWriter::ListWriter as (a) write_entry()'s return type, or (b) the closure parameter for write_entry()'s write_content: impl FnOnce(...)?"

**Comment by barries** [comment]
@zslayton Thanks for the pointer to the draft v1.1 docs. I've read them, love the pending v1.1 features, and have switched to am now playing with the (unstable  :) v1_1 API so I can demo a working prototype apps (log writers and a reader) and track it until it's stable.

However, I'm still struggling with how to pass `ListWriter`s, `StructWriter`s, etc., to closures. To wit, what type `T` do I need? I've delved into the source code and the docs, tried a few things, and can't come up with the correct implementation. `write_content`s can use the `list_writer` for streaming output, or create an ion Serializer for Serde and use it.

Thanks!!!

```rust

type Writer = BinaryWriter<BufWriter>;

pub struct Log {
    pub writer: Writer,
}

impl Log {
    pub fn write_entry<F>(
        &mut self,
        write_content: &F
    )
    where F: FnOnce(&T)                 // <=== goes here to allow...
    {
        use ion_rs::SequenceWriter;
        use chrono::Utc;

        let mut list_writer = self.writer.list_writer().expect("logger ListWriter creation failed");

        write_content(&list_writer);  //  <=== ...this call to compile?

        let _ = list_writer.close();
    }
```

**Comment by zslayton** [comment]
The Rust compiler currently has [an unfortunate limitation around closures](https://blog.rust-lang.org/2022/10/28/gats-stabilization.html#implied-static-requirement-from-higher-ranked-trait-bounds) at the moment. There are several things that should (and will eventually) work, but currently do not. I run into these all the time, and finding ways around them involves a lot of trial and error. Often I'm able to sidestep the issue with a bit of indirection via generics.

Here's a reframing of the problem that the compiler's able to work with:

```rust
mod logging {
    use crate::lazy::encoder::value_writer::internal::MakeValueWriter;
    use crate::{Encoding, IonResult, SequenceWriter, ValueWriter, Writer};

    /// Writes logs in some Ion format `E`.
    pub struct Log<E: Encoding> {
        pub writer: Writer<E, Vec<u8>>,
    }

    #[rustfmt::skip]
    /// A top-level list writer.
    type EventWriter<'a, E> =
        // Viewing the top-level writer as a context where values can be written...
        <<Writer<E, Vec<u8>> as MakeValueWriter>
        // ...this will be the list writer type.
            ::ValueWriter<'a> as ValueWriter>::ListWriter;
    // This is indeed an unfortunately complicated way to have to refer to the type. x_x
    // This type (a list writer) implements `SequenceWriter`.

    /// A trait that acts as a thin wrapper around the desired closure signature,
    /// allowing us to refer to `EventFn<S>` at the usage site. `EventFn<S>` doesn't mention
    /// a mutable reference (`&mut`), sidestepping the compiler's current limitations.
    pub trait EventFn<S>: FnOnce(&mut S) -> IonResult<&mut S>
    // By extending the desired closure trait signature, we guarantee that `EventFn<S>` can be
    // passed anywhere the trait would be accepted.
    where
        S: SequenceWriter,
    {
        fn write_event(self, s: &mut S) -> IonResult<&mut S>;
    }

    // We then implement `EventFn<S>` for all closures with the correct signature,
    // allowing any closure with that signature to be accepted anywhere that `EventFn<S>` is
    // required.
    impl<F, S> EventFn<S> for F
    where
        S: SequenceWriter,
        F: FnOnce(&mut S) -> IonResult<&mut S>,
    {
        fn write_event(self, s: &mut S) -> IonResult<&mut S> {
            self(s)
        }
    }

    impl<Enc: Encoding> Log<Enc> {
        /// Takes a closure that allows the caller to specify the values to write for this event.
        fn write_entry<'f, E>(&'f mut self, event_fn: E) -> IonResult<()>
        where
            E: EventFn<EventWriter<'f, Enc>>,
            // ^^^^^^^ By taking an implementation of `EventFn<_>`,
            // we allow users to pass a closure as expected.
        {
            // Create a list writer
            let mut list_writer = self
                .writer
                .list_writer()
                .expect("logger ListWriter creation failed");
            // Pass it to the user's closure
            event_fn.write_event(&mut list_writer)?;
            // Close it for them afterward, reporting any errors
            list_writer.close()
        }
    }

    #[test]
    fn try_it() {
        use SequenceWriter;
        let mut log = Log {
            writer: Writer::new(crate::v1_1::Text, Vec::new()).unwrap(),
        };
        log.write_entry(|event_writer| {
            event_writer
                .write("Hello")?
                .write(1)?
                .write(true)?
                .write(b"this will be a blob")
        })
        .unwrap();
        let bytes = log.writer.close().unwrap();
        println!("log: {}", String::from_utf8(bytes).unwrap());
    }
}
```

Running the unit test at the bottom produces:
```
log: $ion_1_1 ["Hello", 1, true, {{dGhpcyB3aWxsIGJlIGEgYmxvYg==}}, ] 
```

Please do feel free to toy with the 1.1 APIs, but be warned that the current implementation is lagging behind the spec a bit and is going to continue changing for a least a few more weeks. Data you write out today may not be readable with next week's 1.1 impl. In contrast, the Ion 1.0 encodings are fully stable.

**Comment by barries** [comment]
@zslayton, minor impediment:

```rust
error[E0603]: module `lazy` is private
   --> src\uilog.rs:206:13
    |
206 | use ion_rs::lazy::encoder::value_writer::internal::MakeValueWriter;
    |             ^^^^ private module                    --------------- trait `MakeValueWriter` is not publicly re-exported
    |
note: the module `lazy` is defined here
   --> C:\Users\BarrieSlaymaker\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ion-rs-1.0.0-rc.9\src/lib.rs:189:1
    |
189 | pub(crate) mod lazy;
    | ^^^^^^^^^^^^^^^^^^^
```

**Comment by barries** [comment]
Thanks again for the help, @zslayton. It's compiling and working modulo some "funny" behaviors that I'll open as issues to see if I'm unintentionally violating some invariant(s) or not.
