### ISSUE TITLE
`MakeValueWriter` should be pub and feature-gated

### ISSUE THREAD

**Issue by zslayton** [amazon-ion/ion-rust#863]
@zslayton, minor impediment:

```rust
error[E0603]: module `lazy` is private
   --> src\uilog.rs:206:13
    |
206 | use ion_rs::lazy::encoder::value_writer::internal::MakeValueWriter;
    |             ^^^^ private module                    --------------- trait `MakeValueWriter` is not publicly re-exported
    |
note: the module `lazy` is defined here
   --> C:\Users\BarrieSlaymaker\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ion-rs-1.0.0-rc.9\src/lib.rs:189:1
    |
189 | pub(crate) mod lazy;
    | ^^^^^^^^^^^^^^^^^^^
```

_Originally posted by @barries in https://github.com/amazon-ion/ion-rust/issues/856#issuecomment-2508525321_
            
The change would go here:

https://github.com/amazon-ion/ion-rust/blob/9fd363c91aca0ce87fbd23fbeaef71e35d717719/src/lib.rs#L214-L213

**Comment by barries** [comment]
The `pub use ...` I added feels a bit cheesy. What's the most `ion-rust`ish way to do that?
