### ISSUE TITLE
Provide a pure Rust implementation for Ion 

### ISSUE THREAD

**Issue by therapon** [amazon-ion/ion-rust#99]
Develop a pure Rust implementation for Ion.

**Comment by almann** [comment]
Today, `ion-rs` has a dependency on `ion-c-sys`.  This is purely to "fill" in the implementation for Ion in the most idiomatic Rust APIs.  `ion-c-sys` will focus only on the C bindings, but we should continue to implement a pure Rust implementation in `ion-rs`.  At the time of this writing we have a partial binary parser, for example.  When we have all of the parser/generators, we should eliminate the need to depend on `ion-c-sys`.
